######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 28 12:27:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calc.h kmeans.h mail.h parse.h
SOURCES += calc.c kmeans.c main.c parse.c
